Use QuickBench's recipe caching logic when present
Luligabi1/ProjectTableMod pull request #9
Opened 2024-03-27 19:36 UTC by unilock

This PR adds support for [QuickBench](https://github.com/Modflower/QuickBench) by delegating "shift-click" / `quickMove` crafting logic to it when it's installed. This makes crafting many items at once much, much faster in environments with lots of recipes (e.g. large modpacks).

The mod still works without QuickBench installed; just without the optimizations it provides.

This PR also includes a few minor fixes:
- Unused code has been cleaned up
- Gradle, Loom, and dependencies have been updated

I've tested this PR with All of Fabric 7 both with and without QuickBench. Everything is still working as intended.

2024-03-27 19:57 UTC, unilock commented
It crashes when left-clicking an item out of the result slot instead of shift-clicking items out. I didn't even think to test that. Oh dear.

Closing while I figure this out...

2024-03-27 20:45 UTC, unilock commented
I fixed the issue by rewriting `SimpleRecipeInputInventory` as `DelegateCraftingInventory`, which `extends CraftingInventory` and substitutes `CraftingInventory.stacks` with a provided `Inventory` instance - in this case, the `input` `SimpleInventory` of a `CraftingBlockEntity`.

2024-03-28 01:05 UTC, Luligabi1 commented
I'll take a look at it tomorrow, thanks!

2024-03-28 17:02 UTC, Luligabi1 requested changes
Worked fine on dev env, just some mild concerns and a big one if quickbench is missing 🙂

2024-03-28 17:02 UTC, Luligabi1 commented on gradle.properties
Idk how it happened, but the game won't run unless you update to loader `>=0.15.6`, please change it

2024-03-28 17:02 UTC, Luligabi1 commented on src/main/java/me/luligabi/enhancedworkbenches/common/MixinConfigPlugin.java
> +    public List<String> getMixins() {
is this fine? I've never used mixin plugins before.

2024-03-28 17:02 UTC, Luligabi1 commented on src/main/java/me/luligabi/enhancedworkbenches/common/screenhandler/ProjectTableScreenHandler.java
> +            return MixinHooks.handleShiftCraft(player, this, slots.get(index), input, result, 10, 64);
This most certainly won't work if QuickBench is not present, since `MixinHooks` is imported. I'm not sure if quickbench offers a better solution, best I can think is reflection.

2024-03-28 17:02 UTC, Luligabi1 commented on src/main/java/me/luligabi/enhancedworkbenches/common/screenhandler/CraftingStationScreenHandler.java
> +            return MixinHooks.handleShiftCraft(player, this, slots.get(index), input, result, 10, 46);
.

2024-03-28 17:02 UTC, Luligabi1 commented on src/main/java/me/luligabi/enhancedworkbenches/common/screenhandler/CraftingBlockScreenHandler.java
> +                MixinHooks.slotChangedCraftingGrid(world, input, result);
.

2024-03-28 17:02 UTC, Luligabi1 commented on src/main/java/me/luligabi/enhancedworkbenches/common/screenhandler/DelegateCraftingInventory.java
Code style is inconsistent with rest of project: don't add a space between `if`s/`for`s and their parenthesis nor use `this` unnecesarily. I can fix this myself later though, I don't mean to be asinine 😅

2024-03-28 17:04 UTC, Luligabi1 commented on src/main/java/me/luligabi/enhancedworkbenches/common/MixinConfigPlugin.java
> +    public List<String> getMixins() {
I fucked up while selecting the snippet, I was talking about returning null here 🙂

2024-03-28 17:11 UTC, Luligabi1 commented on src/main/java/me/luligabi/enhancedworkbenches/common/MixinConfigPlugin.java
Doesn't this need to be registered at the mixin file?

2024-03-28 17:22 UTC, unilock commented on src/main/java/me/luligabi/enhancedworkbenches/common/MixinConfigPlugin.java
Sorry, I forgot to remove `MixinConfigPlugin.java` when I removed the self-mixin :v

I'll do that now.

2024-03-28 17:23 UTC, unilock commented on gradle.properties
Probably because I bumped the Fabric API dependency to 0.92.0. I can revert that change.

2024-03-28 17:28 UTC, unilock commented on src/main/java/me/luligabi/enhancedworkbenches/common/screenhandler/DelegateCraftingInventory.java
The rest of the project didn't use `if (...)` vs. `if(...)` consistently, either ;)

2024-03-28 17:31 UTC, unilock commented on src/main/java/me/luligabi/enhancedworkbenches/common/screenhandler/ProjectTableScreenHandler.java
> +            return MixinHooks.handleShiftCraft(player, this, slots.get(index), input, result, 10, 64);
`MixinHooks` won't be classloaded unless that `if` statement returns true, which would only occur if QuickBench is present. `import`s don't exist in bytecode :)

2024-03-28 19:07 UTC, Luligabi1 commented on src/main/java/me/luligabi/enhancedworkbenches/common/screenhandler/DelegateCraftingInventory.java
yeah i probably forgot somewhere, at some point I ought to add checkstyle to my projects to properly enforce it lol

2024-03-28 19:07 UTC, Luligabi1 commented on src/main/java/me/luligabi/enhancedworkbenches/common/screenhandler/ProjectTableScreenHandler.java
> +            return MixinHooks.handleShiftCraft(player, this, slots.get(index), input, result, 10, 64);
right, I probably was thinking of field declarations, sorry

2024-03-28 19:10 UTC, Luligabi1 approved these changes

2024-03-28 19:16 UTC, merged